---
name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Cache var-cache-apt
        uses: actions/cache@v3
        with:
          path: var-cache-apt
          key: var-cache-apt-${{ hashFiles('.github/workflows/test/Dockerfile',  '.github/workflows/test.yml') }}
      - name: Cache var-lib-apt
        uses: actions/cache@v3
        with:
          path: var-lib-apt
          key: var-lib-apt-${{ hashFiles('.github/workflows/test/Dockerfile', '.github/workflows/test.yml') }}
      - name: inject var-cache-apt into docker
        uses: ./
        with:
          cache-source: var-cache-apt
          cache-target: /var/cache/apt
      - name: inject var-lib-apt into docker
        uses: ./
        with:
          cache-source: var-lib-apt
          cache-target: /var/lib/apt
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .github/workflows/test
          push: false
